apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vtuxzs49a-nodejs 
  janus-idp.io/tekton: vtuxzs49a-nodejs
  backstage.io/kubernetes-id: vtuxzs49a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vtuxzs49a-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml